# name: six_cash
# description: A new Flutter application.
# publish_to: 'none' #
# # version: 1.0.0+1
# version: 1.0.1+2

name: six_cash
description: A Flutter app
version: 1.0.2+3


environment:
  # sdk: '>=2.15.0 <3.0.0'
  sdk: '>=2.12.0 <4.0.0'



dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  intl: any
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  shared_preferences: ^2.1.0
  connectivity_plus: ^6.0.2
  firebase_messaging: ^15.2.1
  flutter_local_notifications: ^18.0.1
  path_provider: ^2.1.3
  dotted_border: ^2.1.0
  flutter_contacts: ^1.1.7+1
  azlistview: ^2.0.0
  pin_code_fields: ^8.0.1
  modal_bottom_sheet: ^3.0.0
  slide_to_confirm: ^1.1.0
  lottie: ^3.0.0
  expandable_bottom_sheet: ^1.1.1+1
  smooth_page_indicator: ^1.1.0
  image_picker: ^1.1.0
  country_code_picker: ^3.0.0
  # camera: ^0.11.1
  http: ^0.13.6
  # carousel_slider: ^4.2.1
  carousel_slider: ^5.0.0
  flutter_svg: ^2.0.5
  flutter_html: ^3.0.0-beta.2
  shimmer: ^3.0.0
  permission_handler: ^11.3.1
  share_plus: ^10.1.4
  # screenshot: ^2.3.0
  screenshot: ^3.0.0
  # gallery_saver: ^2.3.2
  modal_progress_hud_nsn: ^0.5.1
  phone_numbers_parser: ^9.0.3
  local_auth: ^2.1.6
  google_mlkit_barcode_scanning: ^0.13.0
  google_mlkit_face_detection: ^0.12.0
  cached_network_image: ^3.3.1
  flutter_secure_storage: ^9.0.0
  app_settings: ^5.1.1
  percent_indicator: ^4.2.3
  flutter_smart_dialog: ^4.9.6+1
  device_info_plus: ^11.2.1
  unique_identifier: ^0.4.0
  url_launcher: ^6.2.6
  flutter_inappwebview: ^6.0.0
  scroll_to_index: ^3.0.1
  flutter_fgbg: ^0.6.0
  firebase_crashlytics: ^4.3.1
  camera: ^0.10.0+1
  firebase_core: ^3.10.1
  avatar_glow: ^3.0.1




  

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3



flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/image/logobuudi.jpeg"

  

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/
    - assets/animationFile/
    - assets/payment/


  fonts:
    - family: Rubik
      fonts:
        - asset: assets/font/Rubik-Light.ttf
          weight: 300
        - asset: assets/font/Rubik-Regular.ttf
          weight: 400
        - asset: assets/font/Rubik-Medium.ttf
          weight: 500
        - asset: assets/font/Rubik-SemiBold.ttf
          weight: 600















# <manifest xmlns:android="http://schemas.android.com/apk/res/android">
#     <!-- io.flutter.app.FlutterApplication is an android.app.Application that
#          calls FlutterMain.startInitialization(this); in its onCreate method.
#          In most cases you can leave this as-is, but you if you want to provide
#          additional functionality it is fine to subclass or reimplement
#          FlutterApplication and put your custom class here. -->


#     <uses-permission android:name="android.permission.INTERNET"/>
#     <uses-permission android:name="android.permission.READ_CONTACTS"/>
#     <uses-permission android:name="android.permission.WRITE_CONTACTS"/>
#     <uses-permission android:name="android.permission.CAMERA"/>
#     <uses-permission android:name="android.permission.RECORD_AUDIO" />
#     <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
#     <uses-permission android:name="android.permission.USE_FINGERPRINT"/>
#     <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
#     <uses-permission android:name="android.permission.READ_PHONE_STATE" />
#     <uses-permission android:name="android.permission.READ_PRIVILEGED_PHONE_STATE" />

#     <queries>
#         <intent>
#             <action android:name="android.intent.action.VIEW" />
#             <data android:scheme="https" />
#         </intent>
#         <intent>
#             <action android:name="android.intent.action.DIAL" />
#             <data android:scheme="tel" />
#         </intent>
#         <intent>
#             <action android:name="android.intent.action.SENDTO" />
#             <data android:scheme="smsto" />
#         </intent>
#         <intent>
#             <action android:name="android.intent.action.SEND" />
#             <data android:mimeType="*/*" />
#         </intent>
#         <intent>
#             <action android:name="android.media.action.IMAGE_CAPTURE" />
#         </intent>
#     </queries>

#     <application
#         android:label="buudi"
#         android:name="${applicationName}"
#         android:requestLegacyExternalStorage="true"
#         android:usesCleartextTraffic="true"
#         android:icon="@mipmap/logobuudi">
#         android:allowBackup="false"
#         android:fullBackupContent="false"


#         <activity
#             android:name=".MainActivity"
#             android:exported="true"
#             android:launchMode="singleTop"
#             android:theme="@style/LaunchTheme"
#             android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
#             android:hardwareAccelerated="true"
#             android:windowSoftInputMode="adjustResize">
#             <!-- Specifies an Android theme to apply to this Activity as soon as
#                  the Android process has started. This theme is visible to the user
#                  while the Flutter UI initializes. After that, this theme continues
#                  to determine the Window background behind the Flutter UI. -->
#             <meta-data
#               android:name="io.flutter.embedding.android.NormalTheme"
#               android:resource="@style/NormalTheme"
#               />
#             <!-- Displays an Android View that continues showing the launch screen
#                  Drawable until Flutter paints its first frame, then this splash
#                  screen fades out. A splash screen is useful to avoid any visual
#                  gap between the end of Android's launch screen and the painting of
#                  Flutter's first frame. -->

#             <meta-data
#                 android:name="com.google.firebase.messaging.default_notification_channel_id"
#                 android:value="6cash" />

#             <meta-data
#               android:name="io.flutter.embedding.android.SplashScreenDrawable"
#               android:resource="@drawable/launch_background"
#               />
#             <intent-filter>
#                 <action android:name="android.intent.action.MAIN"/>
#                 <category android:name="android.intent.category.LAUNCHER"/>
#             </intent-filter>
#             <intent-filter>
#                 <action android:name="FLUTTER_NOTIFICATION_CLICK" />
#                 <category android:name="android.intent.category.DEFAULT" />
#             </intent-filter>
#         </activity>
#         <!-- Don't delete the meta-data below.
#              This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
#         <meta-data
#             android:name="com.google.mlkit.vision.DEPENDENCIES"
#             android:value="ica,ocr,face, barcode" />
#         <meta-data
#             android:name="flutterEmbedding"
#             android:value="2" />


#     </application>
# </manifest>
